### ISSUE TITLE
Don't hardcode usernames

### ISSUE THREAD

**Issue by probonopd** [Artanidos/AnimationMaker#1]
https://github.com/Artanidos/AnimationMaker/blob/3f9275cc254885cc92b5b5c5f4d3b2376c36cda7/Deploy/AppImage/create.sh there seems to be a username hardcoded in paths. Please don't do that since it will not work except on your own machine.

**Comment by Artanidos** [comment]
Even if I install QT somewhere else it will be a path which will only be correct on my workstation.
So I have no idea how to change that.

**Comment by Artanidos** [comment]
file create,sh is not used anymore
