### ISSUE TITLE
1.8.4 not running on LinuxMintDebian (LMDE3) (Stretch)

### ISSUE THREAD

**Issue by magicvince** [Artanidos/AnimationMaker#10]
When I trys to launch the application with command line, I get this message:
```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
Abandon
```

Nothing new after reinstalling the application

**Comment by Artanidos** [comment]
Thank you, I will double check that tomorrow.
Art

Vincent M <notifications@github.com> schrieb am Mi., 5. Juni 2019, 23:15:

**Comment by Artanidos** [comment]
I have now added the libqxcb.so to the setup. Hope that'll help.
