### ISSUE TITLE
How to export to svg?

### ISSUE THREAD

**Issue by j2l** [Artanidos/AnimationMaker#16]
Thanks for this tool.
I don't see any export/save for (animated) or static svg.
Do we need to save as amx? Then?
Thanks

**Comment by j2l** [comment]
@Artanidos I'm sure it's a 2sec reply but I didn't get it :)

**Comment by lavigne958** [comment]
Hi I only know about static svg images, the tool is intended to generate an 'animation' so it exports to a .gif or move file (.avi, ...)
If you know about animated SVG please provide some links here to learn more about it or provide some details please.

**Comment by j2l** [comment]
Hi, sure, check this great project https://github.com/easylogic/editor for svg animation.
