### ISSUE TITLE
Installer not longer provided

### ISSUE THREAD

**Issue by Hattshire** [Artanidos/AnimationMaker#18]
https://github.com/Artanidos/AnimationMaker/blob/43ea702e331f4a5ae98ac9ef8f12cc8e8bf33c6d/plugins/Html/htmlexport.cpp#L22
https://github.com/Artanidos/AnimationMaker/blob/43ea702e331f4a5ae98ac9ef8f12cc8e8bf33c6d/plugins/Html/htmlexport.cpp#L343-L347

**Comment by Artanidos** [comment]
If have added the missing files now.
Sry, for delay. I was without hardware ;-)
