### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by hadmut** [Artanidos/AnimationMaker#19]
Hi,

projects like this usually give some hints in the readme about how to build them. It's a little bit cumbersome to identify all the required  qmake and -dev packages (e.g. for Ubuntu) and steps to build it.

Would be nice to either have a howto (or shell script) to install all needed software and build it, or a Dockerfile to create the required build environment and have things built within. 

regards

**Comment by Artanidos** [comment]
Nice idea.
Would you like to do it?

**Comment by lavigne958** [comment]
Hi @hadmut , I will organise the build chain soon and provide the necessary command lines to build the software.
It will come soon.

**Comment by lavigne958** [comment]
@hadmut it is done, build instructions for linux merged by #23 .

I thought about the docker to build but anyway you need to install the Qt5 libraries to run AnimationMaker so I think it is pointless to build only in a docker environment as we need to install the libraries twice.
