### ISSUE TITLE
Does not compile, serializeableitem.h missing

### ISSUE THREAD

**Issue by probonopd** [Artanidos/AnimationMaker#2]
Does not compile, `serializeableitem.h` missing:
https://travis-ci.org/probonopd/AnimationMaker/builds/222371518#L364-L367

**Comment by Artanidos** [comment]
Thx
Now I have cleaned up the code.

**Comment by probonopd** [comment]
Now getting `encode.cpp:47:33: fatal error: libavutil/timestamp.h: No such file or directory` while trying to compile, https://travis-ci.org/probonopd/AnimationMaker#L467. Please advise.

**Comment by Artanidos** [comment]
You have to install ffmpeg 3.2.2 prior to build.
Don't know if I should provide the include files from ffmpeg also.

**Comment by probonopd** [comment]
Installing the `ffmpeg` package from ` ppa:mc3man/trusty-media` does not seem to solve this for Ubuntu 14.04:

https://github.com/probonopd/AnimationMaker/blob/patch-1/.travis.yml
https://travis-ci.org/probonopd/AnimationMaker/builds/233733848 

Do I have to manually build it as outlined in https://gist.github.com/xdamman/e4f713c8cd1a389a5917?

**Comment by Artanidos** [comment]
I don't think that you have to build it manually, but the includepath should point to the ffmpeg dir.
`INCLUDEPATH += $$PWD/../../ffmpeg-3.2.2`

Or with other words..
I have installed ffmpeg under $HOME/ffmpeg-3.2.2 and my source code is stored at $HOME/SourceCode/AnimationMaker

**Comment by probonopd** [comment]
I don't think that installing the ffmpeg package from ppa:mc3man/trusty-media puts it to `$$PWD/../../ffmpeg-3.2.2` though...

**Comment by Artanidos** [comment]
Nevertheless, I have now added the dependencies (include files and libs)
