### ISSUE TITLE
How to run it in windows?

### ISSUE THREAD

**Issue by ghost** [Artanidos/AnimationMaker#3]
how to get .exe file?

**Comment by Artanidos** [comment]
You will find the version for windows under release 1.1
https://github.com/Artanidos/AnimationMaker/releases/tag/v1.1

**Comment by Suleman-Elahi** [comment]
No longer exists for Windows ?

**Comment by lavigne958** [comment]
Unfortunately i don't have access to a windows computer to build the .exe binary but you should be able to build it manually, simply start QtCreator and open the project. Then build the binary, as far as I remember AnimationMaker does not uses any OS specific code.

**Comment by Suleman-Elahi** [comment]
You can get Windows VPS for free for 1 hour 10 times a day:

https://www.ilovefreesoftware.com/07/tutorial/how-to-get-free-windows-11-vps-with-full-controls.html

**Comment by lavigne958** [comment]
Interesting thanks.
