### ISSUE TITLE
Bundle all non-standard dependencies in AppImage

### ISSUE THREAD

**Issue by probonopd** [Artanidos/AnimationMaker#4]
https://www.linuxhint.com/create-animated-presentations-animationmaker/ says

```
Before we launch app, we need to download some plugins to enable us import, export animation.

# Install Python 2.7 and above if not already installed
sudo apt update && sudo apt install python2.7

# Install ffmpeg as well
sudo apt install ffmpeg

# Change directory to "/home/yourname/animationmaker/plugins". If directory does not exist, then create it
cd /home/<yourname>/animationmaker/plugins

# Download the following files
wget https://github.com/Artanidos/AnimationMaker/releases/download/v1.2/exportXml.py
wget https://github.com/Artanidos/AnimationMaker/releases/download/v1.2/importXml.py

#To export to movie
wget https://github.com/Artanidos/AnimationMaker/releases/download/v1.2/exportMovie.py
```

All of these should be bundled inside the AppImage, since AppImages are supposed to have no dependencies other than what can reasonably be expected to be part of every target system (=distribution) in a recent enough version.

**Comment by Artanidos** [comment]
Yeah, you are right.
I was not able to include python files into an AppImage using linuxdeployqt.
Found out how to use appimagetool... So now I now how to include dependencies :-)

But I am currently working on another solution without the need of python.
I had to skip the idea to use PythonQt because I was not able to compile it on Windows :-(

**Comment by probonopd** [comment]
See Ultimaker Cura for an example application that is written in PythonQt and available for Windows, macOS, and Linux/AppImage. Another one is PrusaControl.

**Comment by Artanidos** [comment]
Thx, but too late.
Just released a new version.
Maybe next time :-)
