### ISSUE TITLE
Qt not found (deb package install)

### ISSUE THREAD

**Issue by devoldski** [Artanidos/AnimationMaker#47]
Missing  dependencies after install 

/usr/bin/animationmaker: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/bin/animationmaker)

**Comment by lavigne958** [comment]
thanks I will update the installer, please what is your current operating system and its version ?

**Comment by devoldski** [comment]
Hi there, Im using elementary OS 5.1.7 Hera, 
From what i understand elementary OS is using Vala and not Qt, so it should not work righth out of the box :-)

I can probably get it to work by installing Qt myself, from my understanding Qt and Vala does not play well together. 

Alfa

**Comment by lavigne958** [comment]
I looked around and yes, elementary os uses Vala and not Qt. I will run a quick test an elementary os to see how it goes too. I think you might get away by installing Qt manually, using their installer. I am still unsure about the libraries path, if you install qt yourself, then you'll need to manually "install" the libraries in the expected path.
I can guide you around.

Edit:

Found you can install qt using snap [here](https://snapcraft.io/install/qt-ubuntu/elementary)
And I found this too, a qt deployer, dont know if it works but worth a try I suppose [qt deployer](https://github.com/QuasarApp/CQtDeployer). I will try it and see.

**Comment by devoldski** [comment]
Thanx, will look into Qt deployer :-) i also found the qt via snap.

**Comment by lavigne958** [comment]
I tried the latest release on ElementaryOS 5.1.7 Hera and I noticed:

- elementary os offer Qt packages so it should be ok and working
- The latest released I made is linked against Qt version 5.12 and not 5.9.5 as I wanted to

I will update the packages with the right version it should be OK after that.

**Comment by devoldski** [comment]
Excellent, will re-download when its updated. Thank you!

**Comment by lavigne958** [comment]
@devoldski I updated the packages in the release section, I tested it on ElementaryOS 5.1.7 and it works. Remember to install `ffmpeg` in order to generate a movie/gif out of your animation :wink: 

You can find your (now with the correct version) package here [Release v1.9.1](https://github.com/Artanidos/AnimationMaker/releases/tag/v1.9.1)

Thank you very much for reporting this issue I would have missed it otherwise.

**Comment by devoldski** [comment]
you are welcome 😁
